### ISSUE TITLE
Missing folder_xml in the folder example

### ISSUE THREAD

**Issue by gitqlt** [joelee2012/api4jenkins#10]
readthedocs.io, Examples, Folder, Create
It would be nice to see an example of a `folder_xml`.
Thanks
[https://api4jenkins.readthedocs.io/en/latest/user/example.html#folder](url)

**Comment by joelee2012** [comment]
thanks for suggestion. i'm working on doc, will add such xml in doc, 
here is version i'm working on: https://api4jenkins.readthedocs.io/en/doc/user/example.html#

**Comment by joelee2012** [comment]
folder xml is placed in example now:https://api4jenkins.readthedocs.io/en/doc/user/example.html#folder
