### ISSUE TITLE
How to get build parameters

### ISSUE THREAD

**Issue by xyl576807077** [joelee2012/api4jenkins#20]
Thanks for your awesome jenkins python wrapper.

I wonder know could we get the build parameters from **Build** class?

**Comment by joelee2012** [comment]
You can't  get build parameters from Build class directly, but you can get the parameters from `api_json`, example code:
```
for action in build.api_json()['actions']:
    if 'parameters' in action:
        print(action)
        break
```
optional you can filter result by setting tree,  `build.api_json(tree='actions[parameters[name,value]]')`

**Comment by joelee2012** [comment]
@xyl576807077  does this answer your question ? by the way,  i will implement this feature in next release.

**Comment by xyl576807077** [comment]
@joelee2012 Thanks for your reply, It works for me!

**Comment by xyl576807077** [comment]
By the way, Is it possible to add retry keyword to avoid intermittent auth error?

**Comment by joelee2012** [comment]
yes, it supports to retry, but seems i forget to add to doc,  see: https://github.com/joelee2012/api4jenkins/blob/master/api4jenkins/requester.py#L18
set `max_retries' when  initialize Jenkins object
```python
j = Jenkins('http://127.0.0.1:8080/', auth=('username', 'password or token'), max_retries=3)
```
