### ISSUE TITLE
How to build with default parameters 

### ISSUE THREAD

**Issue by Peelz** [joelee2012/api4jenkins#23]
Force build with API ```http://<ci-host>/job/<jobname>/buildWithParameters``` instead ```http://<ci-host>/job/<jobname>/build```

**Comment by Peelz** [comment]
OK, I found interim by pass 'foo' variable like 
```python
j.build_job(jn, foo=None)
```
to force using buildWithParameters.

**Comment by joelee2012** [comment]
great, you can read user guide to find more usage
