### ISSUE TITLE
Access lists of nodes from /label/

### ISSUE THREAD

**Issue by baydrift** [joelee2012/api4jenkins#24]
Feature request:
We use pools of nodes, and operate on subsets.
eg "FOO_1", "FOO_2", "BAR"
jenkins:8080/labels/FOO_1&&FOO_2||BAR

In groovy, we use
```
// get a list of nodes, excluding those which are offline (removes 'master')
def nlist = nodesByLabel(label: "${poollist}", offline: `false).sort()
```
Could you add something similar ?
Thanks

**Comment by joelee2012** [comment]
hi, there is no existed function for that,  but it's simple to implement your own, for example the following code can filter nodes by label and print online nodes
```python
j = Jenkins('http://localhost:8080/', auth=('admin', '1234'))


def iter_node_by_label(nodes, labels):
    for node in nodes:
        for label in node.api_json()['assignedLabels']:
            if label['name'] in labels:
                yield node


for node in iter_node_by_label(j.nodes, ['master']):
    if not node.offline:
        print(node)
```

**Comment by joelee2012** [comment]
i will also add some useful functions in lib, see #21

**Comment by baydrift** [comment]
Excellent, thanks.
I'd created this..
`labels = [v['name'] for v in node.api_json()['assignedLabels']]`
