### ISSUE TITLE
Folder description manipulates the All view description

### ISSUE THREAD

**Issue by weshouman** [joelee2012/api4jenkins#27]
`folderJob.description` & `folderJob.set_description()` get and set the `All view`'s description instead of the job folder description.  
If we have multiple views, the other views aren't touched.

**Comment by joelee2012** [comment]
yes, it's same in UI.  you have to edit the configuration of folder to update description.
to update description of other views, you can use `view.description` and `view.set_description('xxx')`

**Comment by weshouman** [comment]
Changing a job's description should literally change the job's description not it's `All view`'s description. Otherwise, if one had important details attached to this view's description it would get wiped out.

For the GUI: I actually find changing the Job's description only through an extra view less intuitive, but that's another topic.

**Comment by joelee2012** [comment]
yes, i know, this lib post description to endpoint `<jekins url>/job/<some folder>/submitDescription` to set description, ideally it should set description for folder, but seems not.

**Comment by weshouman** [comment]
Indeed, running the following command modifies the `All view`'s description too
```
curl -s -XPOST 'http:localhost/PATH/TO/JOB/submitDescription' --data "description=New Description" -H "application/x-www-form-urlencoded" -u "USERNAME:PASSWORD"
```

**Comment by joelee2012** [comment]
yes,  that's what i said. maybe the folder plugin should make some change.
