### ISSUE TITLE
"buildWithParameters"

### ISSUE THREAD

**Issue by Sinutok** [joelee2012/api4jenkins#31]
Hi!
Not a real issue, but I stumbled over the build_job method, which simply do a 
return handle_req('POST', entry, params=params)

Well, "params=params" is quite static, after some digging you always using "**kwargs" down to the Requester-method.
I personally didnt get a build with that method to work, so I had to modify it to
return handle_req('POST', entry, **kwargs)
the strict "params=params" makes no sence to me.

cheers
Matt

**Comment by joelee2012** [comment]
don't know how do you call the method, but the doc may help https://api4jenkins.readthedocs.io/en/latest/user/example.html#project

**Comment by Sinutok** [comment]
I have an example Jenkins-Job which has this Parameter-Definition
.....
   "parameterDefinitions" : [
        {
          "_class" : "hudson.model.ChoiceParameterDefinition",
          "defaultParameterValue" : {
            "_class" : "hudson.model.StringParameterValue",
            "value" : "A"
          },
          "description" : "Auswahlfeld",
          "name" : "TEXT1",
          "type" : "ChoiceParameterDefinition",
          "choices" : [
            "A",
            "B",
            "C"
          ]
        },
        {
          "_class" : "hudson.model.TextParameterDefinition",
          "defaultParameterValue" : {
            "_class" : "hudson.model.StringParameterValue",
            "value" : "Das ist ein Test"
          },
          "description" : "Textfeld",
          "name" : "TEXT2",
          "type" : "TextParameterDefinition"
        }
      ]
.....
  "description" : "API TEST - MG",
  "displayName" : "API-TEST - MG",
  "displayNameOrNull" : null,
  "fullDisplayName" : "API-TEST - MG",
  "fullName" : "API-TEST - MG",
  "name" : "API-TEST - MG",
.....
"Auswahlfeld == Drop-down/Choice-Field"
"Textfeld == String-Input-Field"

I as your doc statet... I do the following
jenkins_server = api4jenkins.Jenkins('https://lvasp-jenkins.example.com', auth=('myuser','99999tokenid9999'),
                             verify=False)
job = jenkins_server.get_job("API-TEST - MG")

using 
item = job.build_job(<whatever>) produces a
builtins.AttributeError: 'FreeStyleProject' object has no attribute 'build_job'
exception

Using a
payload = "TEXT1=C&TEXT2=LLILI"
header = {'Content-Type': "application/x-www-form-urlencoded"}
lauf = jenkins_server.build_job("API-TEST - MG",headers=header,data=payload)
AFTER changing
# ....\site-packages\api4jenkins\job.py 
# Line 137
# from:         resp = self.handle_req('POST', entry, params=params)
# to:          resp = self.handle_req('POST', entry, **params)
 works like a charm

Propably I get something wrong, but in my opinion the fixed hande_req-parameter 'params' didnt work.
and your documentation of .... arg1='string', arg2='string' is sorry... a litte bit irritating.
How about a real example
Do a freestyle-Job like my one, implement a build-With-Parameters and try it.

**Comment by joelee2012** [comment]
try  this :
```python
item = job.build(TEXT1='C', TEXT2='LLILI')
```

**Comment by joelee2012** [comment]
yes, i agree with you the doc should be improved, but unfortunately i don't have time recently. i'm happy if you or someone can help on this.

**Comment by joelee2012** [comment]
yes, i agree with you the doc should be improved, but unfortunately i don't have time recently. i'm happy if you or someone can help on this.

**Comment by Sinutok** [comment]
Sorry wasted your time....got it *facepalm*
I'll post my now running code as example, if someone needs it
jenkins_server = api4jenkins.Jenkins('https://myjenkins.example.com:8443', auth=('someuser','<theapitoken>'),verify=False)
    user = jenkins_server.me.exists()
    version = jenkins_server.version
    print(str(user))
    print(str(version))
    job = jenkins_server.get_job("API-TEST - JOB")
    print(job)
    lauf = job.build(TEXT1="C",TEXT2="lalala")
    print(lauf)

Output:
True
2.277.4
<FreeStyleProject: https://myjenkins.example.com:8443/job/API-TEST%20-%20JOB/>
<QueueItem: https://myjenkins.example.com:8443/queue/item/1149/>

and the jenkis job runs correctly with the Parameters: "C" (of the dropdown-box) and "lalala" (of the text-in-field)
