### ISSUE TITLE
How to get the value of the build parameter ?

### ISSUE THREAD

**Issue by Asa6** [joelee2012/api4jenkins#34]
jenkins api:
http://xxxxxx/job/test/descriptorByName/net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition/fillValueItems?param=

result:
{"_class":"net.uaznia.lukanus.hudson.plugins.gitparameter.model.ItemsErrorModel","errors":[],"values":[{"name":"4b91af67 2020-10-25 18:11 xxxxx <xxxxxxx@xxxx.com> 1. xxxxxxxxxxxxxxxxxxxx","value":"4b91af1111115df6212f1fdsfdsaf4223826f43434"}]}

**Comment by joelee2012** [comment]
to get parameters of build with following code
```python
 paramters = build.get_parameters()
```

**Comment by Asa6** [comment]
I want to get the optional value of the build parameter before the build, not after the build

similar to this:
![image](https://user-images.githubusercontent.com/24604402/139622429-e767f0bd-08b9-4af9-9108-3532b1824379.png)

**Comment by joelee2012** [comment]
try following code
```python
params = []
for p in job.api_json()['property']:
    if 'parameterDefinitions' in p:
        params = p['parameterDefinitions']
```
but for your case, the "${commit}" is variable which will be evaluated during building, so you can't get an exact value for job.

**Comment by Asa6** [comment]
Run the above code, the result is still "${commit}". Is there another way?

**Comment by joelee2012** [comment]
No, because the "${commit}" is bundled with build not the job

**Comment by Asa6** [comment]
Well, thank you for your answer

**Comment by Asa6** [comment]
Sorry, it was caused by my jenkins configuration error. Using job.api_json can get the value correctly

`
params = []
for p in job.api_json()['property']:
    if 'parameterDefinitions' in p:
        params = p['parameterDefinitions']
        print(params)
`
![image](https://user-images.githubusercontent.com/24604402/139817650-1231e3e2-16c8-4423-a4ba-b56ff4b0e805.png)
