### ISSUE TITLE
New versions of Jenkins (V2.307) have renamed "master" to "Built-In Node"

### ISSUE THREAD

**Issue by baydrift** [joelee2012/api4jenkins#35]
https://github.com/joelee2012/api4jenkins/blob/22e3191fdd53ae60ca918a698ff7e5812f6582ba/api4jenkins/node.py#L57

Documented here: https://www.jenkins.io/doc/book/managing/built-in-node-migration/
Checking the displayName and replacing, fixes the issue
```
        for item in self.api_json(tree='computer[displayName]')['computer']:
            if (item['displayName'] == 'Built-In Node'):
                item['displayName'] = '(built-in)' 
```

There is probably a nicer way to do this with 'replace()'

**Comment by baydrift** [comment]
On previous Jenkins versions the name was "master" but the url was "(master)"

**Comment by baydrift** [comment]
Improved, using replace()
 `           item['url'] = f"{self.url}{item['displayName'].replace('Built-In Node', '(built-in)')}/"`

**Comment by joelee2012** [comment]
thanks for reporting this issue, will update this in next release
