### ISSUE TITLE
Differrent server URL

### ISSUE THREAD

**Issue by facetheheat** [joelee2012/api4jenkins#36]
Hi there, 
thanks for useful framework!

**Intro**
I've a nginx proxy with internal httpotp auth for jenkins auth.
For api4jenkins scripts I've used an internal server url, like `http://jenkins:8080/` to skip httpauth for local scripts.
For user auth, I'm using an external server url, like `https://jenkins-in-house.com/`

**The issue.**
For some cases, api4jenkins returns server url described in `Manage Jenkins - Configure System - Jenkins Location - Jenkins URL` instead of initialized object url
```
j = Jenkins('http://the_jenkins:8080/', auth=('automation', 'token'))

print(j)
print(j.url)

for job in j.iter_jobs():
    print(f"job = {job}")
    print(f"name = {name}")

......

<Jenkins: http://the_jenkins:8080/>
http://the_jenkins:8080/

job                 = <WorkflowJob: https://jenkins-in-house.com/job/Just_some_job/>
name             = Just_some_job
```

Is is possible to use server url that initialized for auth, instead of jenkins url?
Thanks!

**Comment by joelee2012** [comment]
As the description of 'Jenkins URL'
> Optionally specify the HTTP address of the Jenkins installation, such as http://yourhost.yourdomain/jenkins/. This value is used to let Jenkins know how to refer to itself, ie. to display images or to create links in emails.
This is necessary because Jenkins cannot reliably detect such a URL from within itself. 

The api4jenkins relies on the response from Jenkins, then item url will start with value of Jenkins URL in system configuration. but you can try following ways:
- create a service account for external url for automation work

- change the item url manually before doing something, eg
    ```python
    internal_url = 'http://jenkins:8080/'
    external_url = 'https://jenkins-in-house.com/'
    j = Jenkins(internal_url)
    print(j)
    for job in j:
        job.url = job.url.replace(external_url, internal_url)
        print(job)

    # output
    # <Jenkins: http://jenkins:8080/>
    # <WorkflowJob: http://jenkins:8080/job/Just_some_job/>
    ```
- check if nginx has configuration to fix issue

**Comment by facetheheat** [comment]
Thanks. 
I've added this external hostname to `/etc/hosts` and all works fine!
```
192.168.224.4 jenkins-in-house.com
```
