### ISSUE TITLE
Get AuthorizationMatrixProperty permissions for each folder

### ISSUE THREAD

**Issue by a-dragos** [joelee2012/api4jenkins#39]
Hello,
How can we get the 'AuthorizationMatrixProperty' (permissions) for each folder configured with matrix-authorization ?
We loop through each folder name, get the config.xml and extract the permissions from the xml tree?
```
# folder config.xml output example:
<com.cloudbees.hudson.plugins.folder.properties.AuthorizationMatrixProperty>
<inheritanceStrategy class="org.jenkinsci.plugins.matrixauth.inheritance.InheritParentStrategy"/>
<permission>com.cloudbees.plugins.credentials.CredentialsProvider.Create:user1example</permission>
.........................................
```

**Comment by joelee2012** [comment]
try access the json data of folder to check if it is there or check if the plugin provide rest api endpoint
```python
print(folder.api_json())
```

**Comment by a-dragos** [comment]
Thank you for your reply!
Just to clarify: _folder_ is an object of the Folder class? 
Do I need to import Folder class, e.g:
```
from api4jenkins import Jenkins, Folder

folder = Folder()
```
Is this the correct approach ?

**Comment by joelee2012** [comment]
yes, it's object, you can get it by following code:
```python
jenkins = Jenkins('url', auth=('u', 'p'))
folder = jenkins.get_job('path/to/your/folder') # or folder = jenkins['path/to/your/folder']
print(folder) 
print(folder.api_json())
```
more usage can be found: https://api4jenkins.readthedocs.io/en/dev/user/example.html#folder

**Comment by a-dragos** [comment]
Thank you! Closing this thread.
