### ISSUE TITLE
Support for jenkins.branch.OrganizationFolder

### ISSUE THREAD

**Issue by capyvara** [joelee2012/api4jenkins#42]
Currently if fails on `_new_instance_by_item()` since the `_class` is `jenkins.branch.OrganizationFolder``

From branch-api-plugin
https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/OrganizationFolder.java

Any workarounds are welcome.

**Comment by joelee2012** [comment]
can you attach the error message? and have you try this https://api4jenkins.readthedocs.io/en/latest/user/example.html#patch ?
