### ISSUE TITLE
After the multi-branch pipeline is disabled, the buildable property has no effect

### ISSUE THREAD

**Issue by shuaibingn** [joelee2012/api4jenkins#46]
I want to disable a multi-branch pipeline, but when I use `disable()`, I find the following problem
1. Multibranch pipeline does not have `buildable` attribute
2. When I disable the multi-branch pipeline, the `buildable` property of the master branch is still `True`

```
multi_branch_pipeline = jenkins.get_job("test_multi_branch")
multi_branch_master = jenkins.get_job("test_multi_branch/master")

print(multi_branch_pipeline.disable())
# print(multi_branch_pipeline.buildable)  # This will raise an exception `AttributeError: 'WorkflowMultiBranchProject' object has no attribute 'buildable'`
print(multi_branch_master.buildable)  # True
```

So how can I get the status of a multi-branch pipeline

**Comment by joelee2012** [comment]
you can get status from `<disabled>true</disabled>` in xml configuration of mulit-branch pipeline:

**Comment by shuaibingn** [comment]
> you can get status from `<disabled>true</disabled>` in xml configuration of mulit-branch pipeline:

Thx, I got it

**Comment by joelee2012** [comment]
i will add new property for mulit-branchpipeline job later
