### ISSUE TITLE
get_build has a bug

### ISSUE THREAD

**Issue by lucatamtam** [joelee2012/api4jenkins#49]
Hi when I call item.get_build() after having started a job the get_build() goes in error.
The stack trace is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/api4jenkins/item.py", line 73, in handle_req
    return self.jenkins.send_req(method, self.url + entry, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/api4jenkins/requester.py", line 28, in send
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myjenkins.mycompany.com/job/APP1/job/APP1_BLABLA/job/APP1_BLABLA_BLABLA/12/api/json?depth=0&tree=queueId

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/Test/Git/myJclient/scripts/job1.py", line 22, in main
    while not item.get_build():
  File "/usr/local/lib/python3.6/site-packages/api4jenkins/queue.py", line 62, in get_build
    if int(build.queue_id) == self.id:
  File "/usr/local/lib/python3.6/site-packages/api4jenkins/item.py", line 129, in __getattr__
    return self.api_json(tree=attr)[attr]
  File "/usr/local/lib/python3.6/site-packages/api4jenkins/item.py", line 68, in api_json
    return self.handle_req('GET', 'api/json', params=params).json()
  File "/usr/local/lib/python3.6/site-packages/api4jenkins/item.py", line 77, in handle_req
    f'Not found {entry} for item: {self}') from e
api4jenkins.exceptions.ItemNotFoundError: Not found api/json for item: <WorkflowRun: https://myjenkins.mycompany.com/job/APP1/job/APP1_BLABLA/job/APP1_BLABLA_BLABLA/12/>

```
I understood the error,  on my jenkins (multinode) some user aborted a job but jenkins did not  delete it from the queue (zombie job in the queue) and the get_build() goes in error.

This is my code:
```
    # Create Jenkins client
    j = Jenkins('https://'+baseurl, auth=(username, password), verify=False)

    # Run build with args
    item = j.build_job(jobname,
        param1=param1_value,
        param2=param2_value,
        param3=param3_value
    )
    # Wait for the queue element
    while not item.get_build():
        time.sleep(1)
```

**Comment by joelee2012** [comment]
this is normal, if catch such exception, the while will be dead loop. you should clean the build from queue.

**Comment by lucatamtam** [comment]
Hi @joelee2012 the jenkins instance is used by more than 200 person, and I'm not the owner/admin of the jenkins.
There isn't a way to ignore the zombie jobs when I'm trying to get my build instance?

Thanks you

**Comment by joelee2012** [comment]
can you verify if the fix works ? cause i don't have env to verify

**Comment by joelee2012** [comment]
@lucatamtam are you able to verify ? i can't reproduce the issue

**Comment by lucatamtam** [comment]
hi @joelee2012 yes the fix is working thanks you

**Comment by joelee2012** [comment]
@JakubBiel you can enable debug log to check what happened during error/long time response.

**Comment by joelee2012** [comment]
@JakubBiel you can enable debug log to check what happened during error/long time response.

**Comment by JakubBiel** [comment]
build = item.get_build()

DEBUG:api4jenkins.requester:GET: https://<url>/queue/item/528362/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /queue/item/528362/api/json?depth=0 HTTP/1.1" 200 628
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/queue/item/528362/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0, 'tree': '_class'}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /queue/item/528362/api/json?depth=0&tree=_class HTTP/1.1" 200 63
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/computer/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 2,
            'tree': 'computer[executors[currentExecutable[url]],oneOffExecutors[currentExecutable[url]]]'}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /computer/api/json?depth=2&tree=computer%5Bexecutors%5BcurrentExecutable%5Burl%5D%5D%2ConeOffExecutors%5BcurrentExecutable%5Burl%5D%5D%5D HTTP/1.1" 200 327
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/job/<project>/job/main/23/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0, 'tree': '_class'}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /job/<project>/job/main/23/api/json?depth=0&tree=_class HTTP/1.1" 200 72
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/job/<project>/job/main/23/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0}}

hangs for 4 minutes

DEBUG:urllib3.connectionpool:https://<url>:443 "GET /job/<project>/job/main/23/api/json?depth=0 HTTP/1.1" 200 4993
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/job/<project>/job/main/23/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0, 'tree': 'queueId'}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /job/<project>/job/main/23/api/json?depth=0&tree=queueId HTTP/1.1" 200 89
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/job/<job>/job/master/5/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0, 'tree': '_class'}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /job/<job>/job/master/5/api/json?depth=0&tree=_class HTTP/1.1" 200 72
DEBUG:api4jenkins.requester:Response: <Response [200]>
DEBUG:api4jenkins.requester:GET: https://<url>/job/<job>/job/master/5/api/json with parameters: {'headers': {'Jenkins-Crumb': 'crumb'},
 'params': {'depth': 0, 'tree': 'queueId'}}
DEBUG:urllib3.connectionpool:https://<url>:443 "GET /job/<job>/job/master/5/api/json?depth=0&tree=queueId HTTP/1.1" 200 89
DEBUG:api4jenkins.requester:Response: <Response [200]>
[SUCCESS] You have successfully triggered the job.

**Comment by JakubBiel** [comment]
I realised that the 'project' in `https://'url'/job/'project'/job/main/23/api/json` is a different one to the one that is being triggered here.
