### ISSUE TITLE
api4jenkins does not support requests 2.10

### ISSUE THREAD

**Issue by davidelka** [joelee2012/api4jenkins#51]
api4jenkins does not include version dependency for requests library -
 it's not supported older version (at least requests 2.10)
 
 api4jenkins should include version dependency

**Comment by davidelka** [comment]
On my machine was installed requests 2.10
and it raiser:
"with self.handle_req('GET', '') as resp: AttributeError: __enter__"

when I update the requests library (to 2.21.1) the issue was solved

**Comment by joelee2012** [comment]
@davidelka  thanks for reporting this issue, will fix it in next release.
