### ISSUE TITLE
Is there any method to dump build parameters to JSON or YAML file

### ISSUE THREAD

**Issue by samsun639** [joelee2012/api4jenkins#53]
If there is an API to dump build parameters to JSON/YAML file, will help a lot for next time build job.

Thanks!

**Comment by joelee2012** [comment]
yes, the build object has method `get_parameters`, see api doc

**Comment by samsun639** [comment]
> 

Thanks for the quik reply, I noticed get_parameters method, looks like it will return a list.
if there's  dump method will be great. e.g.  build.dump("params.json")

**Comment by samsun639** [comment]
OR If `get_parameters` can return dict that can be directly used by job.build will also be great.

**Comment by joelee2012** [comment]
No, you have to construct parameters by yourself for next build.
can you describe your requirement ?

**Comment by samsun639** [comment]
Senario like:
Reuse paramters of a known build which contains large number of parameters, e.g. 30 parameters. And only change serveral parameters of it for next builds

The current return value of `buid.get_parameters()` are not easy for re-construction for next builds.

**Comment by samsun639** [comment]
I have wrote a function to convert parameters to dict and then save a yaml file.
