### ISSUE TITLE
utf-8 support

### ISSUE THREAD

**Issue by fz0000** [joelee2012/api4jenkins#54]
https://github.com/joelee2012/api4jenkins/blob/457129271c21ed30bcc9d4278a0233031ef15249/api4jenkins/job.py#L59-L61
If the job xml contains non-ascii characters, it may cause an error.
So I suggest using
```python
    def create(self, name, xml):
        return self.handle_req('POST', 'createItem', params={'name': name},
                               headers=self.headers, data=xml.encode('utf-8'))
```

**Comment by joelee2012** [comment]
encode/decode can be done when setting parameters to functions. eg.
```python
folder.create('new', xml.encode('utf-8'))
```

**Comment by fz0000** [comment]
How about `duplicate`?
e.g. 
```python
from api4jenkins import Jenkins

server = Jenkins('http://<address>:8080/', auth=('user', 'password'))
j = server.get_job('test')
j.duplicate('test2')
```
![jenkins](https://user-images.githubusercontent.com/5061311/176148567-775e5aaa-ffa0-48d2-b5b2-60b514283ee8.png)

So if I need to copy a job, I have to use `create` instead? Any better solutions?

By the way, this issue does not occur when run in pycharm.

**Comment by joelee2012** [comment]
yes, you are right. i will create a PR for this issue.

**Comment by joelee2012** [comment]
You are right. i will create a PR for this issue.
