### ISSUE TITLE
The optional param "recursive" is missing in some functions

### ISSUE THREAD

**Issue by fz0000** [joelee2012/api4jenkins#55]
The `recursive` is added in `create_job` in #48. So other related functions need to add it, too:

---
update
https://github.com/joelee2012/api4jenkins/blob/457129271c21ed30bcc9d4278a0233031ef15249/api4jenkins/__init__.py#L126
to
```python
self.create_job(folder.full_name, EMPTY_FOLDER_XML, recursive=recursive)
```
---
and update
https://github.com/joelee2012/api4jenkins/blob/457129271c21ed30bcc9d4278a0233031ef15249/api4jenkins/job.py#L34-L35
to
```python
def duplicate(self, path, recursive=False):
    self.jenkins.create_job(path, self.configure(), recursive=recursive)
```

**Comment by joelee2012** [comment]
are you able to create PR for this issue ?
