### ISSUE TITLE
Authentication with pre-existing api token

### ISSUE THREAD

**Issue by therobotcarlson2** [joelee2012/api4jenkins#6]
Great library! It would be great to enable the use of existing api tokens so usernames / passwords aren't passed around in plaintext. Something like:
```
j = Jenkins(url, api_token="xyz")
```
Would preserve backwards compatibility

**Comment by joelee2012** [comment]
yes, the token is supported, just replace the password with token, 
```python
# authenticate with token
j = Jenkins(url, auth=('username', 'your token'))
# or you can use dynamic token
j = Jenkins(url, auth=('username', 'your password'), token=True)
```
see https://api4jenkins.readthedocs.io/en/latest/user/api.html#api4jenkins.Jenkins

**Comment by therobotcarlson2** [comment]
I missed that! That would be a great example to add to the documentation. Seems to be working just fine. Thank you so much!

**Comment by joelee2012** [comment]
I would like to add more examples, however i don't have time recently. if you are interesting and can help on this that will be great :smile:

**Comment by hp77-creator** [comment]
Hey @joelee2012 , I am trying the way it's mentioned in the `docs` for passing token, like following:
`server = Jenkins(JENKINS_URL, auth=(USER, API_KEY), token=True)`

I am getting the following error:
```
TypeError: __init__() got an unexpected keyword argument 'token'
```

I checked the `Jenkins` but can't see any mention of `token` there
I am using following version:
```
api4jenkins        2.0.3
```

Can you help me here?

**Comment by hp77-creator** [comment]
I saw ur comment above and replaced API_KEY with PASSWORD but still same error,  and If I just try USER and API_TOKEN, I get a 401

**Comment by joelee2012** [comment]
@hp77-creator parameter `token`  is only available in 1.x and for dynamic token only. if you are using 2.x,  do like:
```python
client = Jenkins(url, auth=(username, password|token))
```
