### ISSUE TITLE
Build number included string occured error.

### ISSUE THREAD

**Issue by JayChanggithub** [joelee2012/api4jenkins#62]
Hi Support, 

i got error from `smoke-test_1  |   File "/usr/local/lib/python3.10/site-packages/api4jenkins/job.py", line 159, in get_build
smoke-test_1  |     if int(number) == int(item['number']):
smoke-test_1  | ValueError: invalid literal for int() with base 10: '1521-sit02-master'` Because our build number included string. Have anything possible to fix? 

`
File "/usr/local/lib/python3.10/site-packages/api4jenkins/job.py", line 159, in get_build
smoke-test_1  |     if int(number) == int(item['number']):
`

remove int transition? thanks 

<img width="304" alt="Screen Shot 2022-09-15 at 16 35 17" src="https://user-images.githubusercontent.com/36335960/190356463-7c136650-5f7f-4034-ae1e-28dd5d29b15d.png">

**Comment by joelee2012** [comment]
`1521-sit02-master` is display name of build,  open the build in browser and you will see real build number in address bar.

**Comment by JayChanggithub** [comment]
have anything object can got exactly number? Thanks.

**Comment by JayChanggithub** [comment]
Hi fix issue by buildno attribute. Thanks.

**Comment by joelee2012** [comment]
@JayChanggithub this PR will enable `job.get_build` to return build by display name

**Comment by JayChanggithub** [comment]
Thanks @joelee2012. Got it
