### ISSUE TITLE
Approving the Pending Input is not working when Jenkins runs on Subpath

### ISSUE THREAD

**Issue by cybersa** [joelee2012/api4jenkins#66]
I have configured the Jenkins instance to run on subpath using this configuration --prefix=$PREFIX (https://www.jenkins.io/doc/book/installing/initial-settings/#networking-parameters). 

When i try to approve the Jobs, its failing with following error:

> Sep 27 10:45:12 jenkins python[216706]: 2022-09-27 10:45:12,892 DEBUG POST: https://localhost/jenkins//jenkins/job/Test_QA_PL/3/input/D429835560e9194da64fefbc4517f23f/proceedEmpty with parameters: {'headers': {'Jenkins-Crumb': 'xxxx'}}
Sep 27 10:45:12 jenkins python[216706]: 2022-09-27 10:45:12,965 DEBUG https://localhost:443 "POST /jenkins//jenkins/job/Test_QA_PL/3/input/D429835560e9194da64fefbc4517f23f/proceedEmpty HTTP/1.1" 404 526
Sep 27 10:45:12 jenkins python[216706]: 2022-09-27 10:45:12,966 DEBUG Response: <Response [404]>
Sep 27 10:45:12 jenkins python[216706]: 2022-09-27 10:45:12,966 INFO sqlalchemy.engine.Engine ROLLBACK
Sep 27 10:45:12 jenkins python[216706]: 2022-09-27 10:45:12,966 INFO ROLLBACK
Sep 27 10:45:12 jenkins python[216706]: 2022-09-27 10:45:12,966 ERROR Exception on /jira [POST]
Sep 27 10:45:12 jenkins python[216706]: Traceback (most recent call last):
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/api4jenkins/item.py", line 73, in handle_req
Sep 27 10:45:12 jenkins python[216706]:     return self.jenkins.send_req(method, self.url + entry, **kwargs)
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/api4jenkins/requester.py", line 28, in send
Sep 27 10:45:12 jenkins python[216706]:     resp.raise_for_status()
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
Sep 27 10:45:12 jenkins python[216706]:     raise HTTPError(http_error_msg, response=self)
Sep 27 10:45:12 jenkins python[216706]: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://localhost/jenkins//jenkins/job/Test_QA_PL/3/input/D429835560e9194da64fefbc4517f23f/proceedEmpty
Sep 27 10:45:12 jenkins python[216706]: The above exception was the direct cause of the following exception:
Sep 27 10:45:12 jenkins python[216706]: Traceback (most recent call last):
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
Sep 27 10:45:12 jenkins python[216706]:     response = self.full_dispatch_request()
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
Sep 27 10:45:12 jenkins python[216706]:     rv = self.handle_user_exception(e)
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
Sep 27 10:45:12 jenkins python[216706]:     rv = self.dispatch_request()
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
Sep 27 10:45:12 jenkins python[216706]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/server.py", line 61, in jira_parse
Sep 27 10:45:12 jenkins python[216706]:     jira_parser.parse(data)
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/jira_parser.py", line 84, in parse
Sep 27 10:45:12 jenkins python[216706]:     self.request_approved(jira_id,service,environment)
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/jira_parser.py", line 142, in request_approved
Sep 27 10:45:12 jenkins python[216706]:     if self.jenkins.approve_job(job_name):
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/jenkins_utils.py", line 89, in approve_job
Sep 27 10:45:12 jenkins python[216706]:     build.get_pending_input().submit()
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/api4jenkins/input.py", line 43, in submit
Sep 27 10:45:12 jenkins python[216706]:     return self.handle_req('POST', 'proceedEmpty')
Sep 27 10:45:12 jenkins python[216706]:   File "/opt/build_automator/venv/lib/python3.10/site-packages/api4jenkins/item.py", line 76, in handle_req
Sep 27 10:45:12 jenkins python[216706]:     raise ItemNotFoundError(
Sep 27 10:45:12 jenkins python[216706]: api4jenkins.exceptions.ItemNotFoundError: Not found proceedEmpty for item: <PendingInputAction: https://localhost/jenkins//jenkins/job/Test_QA_PL/3/input/D429835560e9194da64fefbc4517f23f/>

**Comment by joelee2012** [comment]
thanks for fixing the issue
