### ISSUE TITLE
proxy agent setting

### ISSUE THREAD

**Issue by JayChanggithub** [joelee2012/api4jenkins#69]
Hi ,

Have anything else possible added proxy items when creating Jenkins(url=, proxy='') like these. Because of some landscaped requirement setup proxy. Thanks. 

```bash
proxies = {
   'http': 'http://proxy.example.com:8080',
   'https': 'http://secureproxy.example.com:8090',
}

url = 'http://mywebsite.com/example'

response = requests.post(url, proxies=proxies)

```

**Comment by joelee2012** [comment]
yes, as [doc](https://api4jenkins.readthedocs.io/en/latest/user/example.html) mentioned, you can set any parameters supported by [request](https://requests.readthedocs.io/en/latest/api/#requests.Session.request)

**Comment by JayChanggithub** [comment]
Thanks. Let me check.!

**Comment by JayChanggithub** [comment]
Hi @joelee2012  

i got these also via proxies to do as below, have anything else concern?

```bash
from api4jenkins import Jenkins as jenksapi
proxies = {
   'http': 'http://tunnel-http-proxy.pipeline-tunnel:8080'
}
client = jenksapi(
    url,
    auth=(
        username,
        password
    ),
    verify=False,
    max_retries=10,
    proxies=proxies
)

```

**Comment by joelee2012** [comment]
does it report error ?

**Comment by JayChanggithub** [comment]
It's find also workable. But let me see if I understand it correctly?

**Comment by joelee2012** [comment]
yes, you are correct

**Comment by JayChanggithub** [comment]
Thanks for your clarifying.
