### ISSUE TITLE
build.queue_id + 1 not always equals to queue.id

### ISSUE THREAD

**Issue by YxxY** [joelee2012/api4jenkins#7]
line 59 in queue.py
```python 59
if int(build.queue_id) + 1 == self.id:
```
this rule does not take effect all the time, but I don't find the patterns either……

**Comment by joelee2012** [comment]
are you able to show an example ?

**Comment by YxxY** [comment]
@joelee2012 my jenkins server version is v2.204.2
I can reproduce this bug every single time by the following code
```python
queue = j.queue
for item in queue:
    print(item, item._class)
    try:
        job = item.get_job()
        print(job)
    except Exception as e:
        print(e)
```
**most** of the `BuildableItem` can not get the right build，
in my case, the relationship between queue_id and id is 
```
build.queue_id -> queue.id
9929132 -> 9929136
9929557 -> 9930388
9929603 -> 9930389
```
only a few of them match `int(build.queue_id) + 1 == self.id`

**Comment by joelee2012** [comment]
@YxxY  interesting, are you able to capture json of build, queue item, computer ? i will check.

**Comment by joelee2012** [comment]
@YxxY  is issue still there ?

**Comment by YxxY** [comment]
sorry,  I just want to distinguish the running build from the queuing build, I have done it in another way.

**Comment by YxxY** [comment]
I may close the issue first, sorry to bother

**Comment by joelee2012** [comment]
Ok, that's great.
are you able to share your solution if possible ? i would like to fix any bug.
