### ISSUE TITLE
Please document 100 job limit on get_build(number)

### ISSUE THREAD

**Issue by baydrift** [joelee2012/api4jenkins#78]
After https://github.com/joelee2012/api4jenkins/issues/33
Can the limit of 100 jobs be documented ?

I spent quite a while debugging why I couldn't get a job which I knew was valid. Turns out it was older than 100 jobs.
Even better would be an optional parameter (default to 100) which forces the user to think and can define more if required.

**Comment by joelee2012** [comment]
@baydrift It was documented for `job.iter_builds()`,  another function `iter_all_builds` can iterate all builds. 
Welcome to create PR to make it better
