### ISSUE TITLE
jenkins.get_job().build(with parameters)

### ISSUE THREAD

**Issue by JohnyCapo** [joelee2012/api4jenkins#79]
Hello,

please, could you help me with my little issue? I'm trying to trigger build with one parameter.

'defaultParameterValue': {'_class': 'hudson.model.BooleanmParameterValue', 'name': 'UT', 'value': False}

I have tried:
.build(params=True)
.build(params=[True])
.build(params={'UT': True})
.build(params=[{'name': 'UT', 'value': True])

I wonder, should I completely copy job.get_parameters() and somehow change the value? Thank you.

**Comment by joelee2012** [comment]
@JohnyCapo here is example: https://api4jenkins.readthedocs.io/en/latest/user/example.html#project
