### ISSUE TITLE
Cannot get the specify build use get_build(number)

### ISSUE THREAD

**Issue by shuaibingn** [joelee2012/api4jenkins#81]
I know that only the first 100 builds are obtained now, but get_build(number) should be free to specify the build number to be reasonable

```
def get_build(self, number):
    for item in self.api_json(tree='allBuilds[number,displayName,url]')['allBuilds']:
        if number == item['number'] or number == item['displayName']:
            return self._new_instance_by_item('api4jenkins.build', item)
    return None
```
So it should be fine to change it to the above, except that it may be slower

**Comment by joelee2012** [comment]
@shuaibingn thanks for creating PR. However as described in api doc: https://ci.jenkins.io/job/Core/job/jenkins/job/master/api/
```quote
Retrieving all builds

To prevent Jenkins from having to load all builds from disk when someone accesses the job API, the builds tree only contains the 50 newest builds. If you really need to get all builds, access the allBuilds tree, e.g. by fetching …/api/xml?tree=allBuilds[…]. Note that this may result in significant performance degradation if you have a lot of builds in this job. 
```
so it does not make sense to get all builds by default, instead you can use another method `job.iter_all_builds`

**Comment by shuaibingn** [comment]
> @shuaibingn thanks for creating PR. However as described in api doc: https://ci.jenkins.io/job/Core/job/jenkins/job/master/api/
> 
> ```
> Retrieving all builds
> 
> To prevent Jenkins from having to load all builds from disk when someone accesses the job API, the builds tree only contains the 50 newest builds. If you really need to get all builds, access the allBuilds tree, e.g. by fetching …/api/xml?tree=allBuilds[…]. Note that this may result in significant performance degradation if you have a lot of builds in this job. 
> ```
> 
> so it does not make sense to get all builds by default, instead you can use another method `job.iter_all_builds`

I found such an API after looking at the jenkins api
`job_name/<build_number>/api/json`
Should be able to get specific builds faster

Using such an API in the latest submission, I rewrote the `api_json()` method in `Job` so that it can support the param url

**Comment by joelee2012** [comment]
Don't do that since it makes misunderstanding and additional complex
