### ISSUE TITLE
[FEATURE REQUEST] Credentials domains

### ISSUE THREAD

**Issue by vittoriocanilli** [joelee2012/api4jenkins#90]
Currently _api4jenkins_ supports to manage system and folder based credentials, which must be in  the default domain(_).

It would be great if _api4jenkins_ could manage credentials in different domains and if it could even manage credentials domains. 

Another Python package, [python-jenkins](https://python-jenkins.readthedocs.io/en/latest/), can handle credentials in all domains, but it can not manage system credentials and credentials in GitHub organization folders. Therefore I am using now _api4jenkins_.

I brought up the other package just to point out that credentials domains managements could be implemented here too.

**Comment by joelee2012** [comment]
@vittoriocanilli it does make sense, i was thinking this but did not done, maybe in next release
