### ISSUE TITLE
v2.0.0 syntax errors when using Python 3.7 due to walrus operator

### ISSUE THREAD

**Issue by srdennett** [joelee2012/api4jenkins#95]
Version 2.0.0 includes changes that use the walrus operator (`:=`), but setup.py still has `python_requires='>=3.7'`. Since the walrus operator was introduced in Python 3.8, this causes syntax errors upon import. 

```python
>>> import api4jenkins
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/conda-envs/py37/lib/python3.7/site-packages/api4jenkins/__init__.py", line 160
    if job := self.get_job(full_name):
            ^
SyntaxError: invalid syntax
```

**Comment by joelee2012** [comment]
@srdennett thanks for reporting issue.  
It should be 3.8, since 3.7 is EOL, https://endoflife.date/python, i will fix this in next release.

**Comment by joelee2012** [comment]
@srdennett release 2.0.1 includes the fix.
