### ISSUE TITLE
Unable to control the logger from v.2.0.0 or newer

### ISSUE THREAD

**Issue by vittoriocanilli** [joelee2012/api4jenkins#97]
In my application I am using the Python _logging_ library and it was not having problems with _api4jenkins_ till the version `v1.15.0`. As soon as I have started using a newer version, I get such messages in my logs for all operations:
```shellscript
2023-12-12 16:09:36 INFO     HTTP Request: GET https://jenkins.mycompany.com/crumbIssuer/api/json "HTTP/1.1 200 OK"
2023-12-12 16:09:36 INFO     HTTP Request: HEAD https://jenkins.mycompany.com/ "HTTP/1.1 200 OK"
2023-12-12 16:09:36 INFO     HTTP Request: GET https://jenkins.mycompany.com/user/myuser/api/json?depth=0 "HTTP/1.1 200 OK"
2023-12-12 16:09:36 INFO     HTTP Request: GET https://jenkins.mycompany.com/user/myuser/api/json?depth=0&tree=id "HTTP/1.1 200 OK"
2023-12-12 16:09:36 INFO     HTTP Request: GET https://jenkins.mycompany.com/user/myuser/api/json?depth=0&tree=absoluteUrl "HTTP/1.1 200 OK"
2023-12-12 16:09:36 INFO     HTTP Request: GET https://jenkins.mycompany.com/user/myuser/api/json?depth=0&tree=fullName "HTTP/1.1 200 OK"
```

It looks like sometimes these logs even lead to a `The read operation timed out` error which interrupts my application. I have tried to control the logger as follows:

```python
import logging
...
jenkins_logger = logging.getLogger('api4jenkins')
jenkins_logger.setLevel(logging.CRITICAL)
```

but whatever log level I set, I still get the same high amount of log messages. The last 2 rows above were not necessary in the `v1.15.0` version.

I am using Python `3.10.13` and I have encountered this issue with _api4jenkins_ `v2.0.0`, `v2.0.1` and `v2.0.2`. These versions have 3 loggers: api4jenkins.item, api4jenkins and api4jenkins.http. Instead the `v1.15.0` version has 2 loggers: api4jenkins.requester and api4jenkins.

**Comment by joelee2012** [comment]
@vittoriocanilli  `logger` in `item.py` is unnecessary, i will remove the line.  but how to reproduce the issue, are you able to share more detail ?

**Comment by vittoriocanilli** [comment]
@joelee2012 I have found out how to mute the logs, as I have seen in the change logs that `requester` has been replaced by `httpx`:

```python
import logging
...
jenkins_logger = logging.getLogger('httpx')
jenkins_logger.setLevel(logging.CRITICAL) # even logging.ERROR will be fine
```

But it looks like it wasn't the excessive logs leading to the application error, as I assumed previously. I actually get a **httpx.ReadTimeout** exception with `The read operation timed out` as message when I try to update a job (a GitHub organization in my case) with the following command:

```python
from api4jenkins import Jenkins
j = Jenkins('http://127.0.0.1:8080/', auth=('username', 'password or token'))
j.get_job('my_github_org').configure("<?xml version='1.1' encoding='UTF-8'?><my_github_org_xml/>")
```

It succeed sometimes, but it fails 80% of the times, while it always worked with the `v1.15.0` version. Is there a way to set a higher timeout? I did not change anything on my Jenkins instance.

**Comment by vittoriocanilli** [comment]
@joelee2012 eventually I have found this [paragraph](https://github.com/joelee2012/api4jenkins/blob/main/docs/source/user/example.rst?plain=1#L26-L27) in the documentation, which leads to more information on [using HTTPX ](https://www.python-httpx.org/api/#client), so I could find out how to set its timeout.

Just to recap, here is how I solved the issues:
```python
import logging
from api4jenkins import Jenkins
...
httpx_logger = logging.getLogger('httpx') # <- setting HTTPX log level
httpx_logger.setLevel(logging.CRITICAL) # <- setting HTTPX log level
...
j = Jenkins('http://127.0.0.1:8080/', auth=('username', 'password or token'), timeout=10) # <- setting HTTPX timeout
j.get_job('my_github_org').configure("<?xml version='1.1' encoding='UTF-8'?><my_github_org_xml/>")
```
