### ISSUE TITLE
WorkflowJob object has no attribute 'get_build'

### ISSUE THREAD

**Issue by facetheheat** [joelee2012/api4jenkins#99]
Hi there,
I upgraded from version 1.15 to 2.0 and get an issue, the method get_build() is missing.

```py
def get_build_data_by_number(self, job_name: str, build_number: int):
    """ Route Jenkins: Get build data by build number """
    job_item = self.get_job(job_name)
    if job_item:
      build_item = job_item.get(build_number)
    if build_item:
      return build_item.api_json()
    return False
```

How can I retreive information on a specific build from job?
Thanks

**Comment by joelee2012** [comment]
@facetheheat it was renamed to `get`, but the doc was not updated yet

**Comment by facetheheat** [comment]
Thanks, `iter_builds` also renamed to `iter_all_builds`
